### ISSUE TITLE
SyntaxError: 

### ISSUE THREAD

**Issue by dgnorris30** [amarvin/fantasy-football-bot#19]
File "scraper.py", line 106
    writer.writerow([pid, name, team, position, roster0, owner, *points])
                                                                                                ^
SyntaxError: invalid syntax

Is this because the season has not started yet, and it is getting a null value or something. My python skills are week...
Python version: 2.7.15

**Comment by amarvin** [comment]
Thanks for your interest in this repo! I don't think Python 2 will work. Could you try it in Python 3? The list unpacking syntax I used `*points` is only in Python 3, I think.

**Comment by dgnorris30** [comment]
great thanks.. Python3 worked for me once i installed requirements.txt and added chromedriver to my path.
