### ISSUE TITLE
Error - Scraper.py - Not enough values to unpack

### ISSUE THREAD

**Issue by Incogneat01234** [amarvin/fantasy-football-bot#21]
Console is returning the following code after running for about a minute:
```
Traceback (most recent call last):
  File "scraper.py", line 167, in <module>
    any_players = parse_table(trs, owner_col_offset=owner_col_offset)
  File "scraper.py", line 91, in parse_table
    team, position = div2.find_element_by_xpath('.//span').text.split(' - ')
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by amarvin** [comment]
Hmm, I can't reproduce this error. Could you try it again?

I really want to move away from scraping using the Chrome Driver + Selenium, as I sometimes also get errors. I use these tools to ensure that the stat tables get populated before I scrape the data, although there must be other end-points or methods to scrape this data using just the Requests module. The R "load" library apparently waits for tables to populate, as I found this implementation of scraping Yahoo Fantasy Football stats tables: https://github.com/FantasyFootballAnalytics/FantasyFootballAnalyticsR/blob/master/R%20Scripts/Weekly%20Projections/Yahoo.R.

**Comment by Incogneat01234** [comment]
Ran it again, same results. Not sure what is causing that issue. You can check if you like, the league is public so it doesn't require a sign in. 15604.

**Comment by amarvin** [comment]
I'm working on a fix for you to support public leagues without sign-in. The upgrade to `scraper.py` should work for both of us. I'll need to make a separate update to `optimize.py` as my league settings (e.g. roster positions) are hardcoded into it.

**Comment by amarvin** [comment]
Try the latest `scraper.py`

**Comment by Incogneat01234** [comment]
Running now

**Comment by Incogneat01234** [comment]
Looks like it works! Yahoo gets pissy about too many requests however, and starts rejecting requests after too many players are scraped. I am running into this issue html scraping projections from VBA as well. 

If a trade-finder is to be built, it would also be wise to scrape all taken players. Easy enough to implement, just use the code you currently have for scraping and replace status=A to status=T in the url. 

For analyzing free agents, I dont think you need to scrape so many players. Top 25 rest of season projected at each position should do the trick for most leagues. Anything beyond those will likely not have enough projected pts to justify dropping a player currently on your roster for them. 

Thanks for the quick turnaround on all this. I have mostly coded within Excel VBA and this has made me think about branching into python or R.

**Comment by Incogneat01234** [comment]
No doubt, you are in an enviable position with where you are at for yahoo leagues because you already have the two hardest parts done for any tool you wish to build - weekly projection import and lineup optimization. 

I'm telling ya, a trade finder for 1x1, 2x2, and 3x3 trades which takes advantage of yahoo's trade eval screen to show win-win trades is a league-winner.
