### ISSUE TITLE
Hanging at "Scraping weekly forecasts"

### ISSUE THREAD

**Issue by Incogneat01234** [amarvin/fantasy-football-bot#41]
As title suggests, the script is hanging on scraping weekly forecasts  
Scraping all QB... 
Scraping all WR... 
Scraping all RB... 
Scraping all TE... 
Scraping all DEF... 
Scraping weekly forecasts...  

I've let it sit for nearly an hour. I know from last year this shouldnt take this long. Just wanted to let you know. Public league ID 39617. All I am trying to do is scrape projections and save at this point.

**Comment by amarvin** [comment]
Thanks for letting me know, and sorry the script is hanging for you. That step of the script grabs the forecast table that's displayed when you click the icon next to any player. A 3rd-party, not Yahoo, creates the forecasts and it looks like all the forecasts are currently zero. I'm not able to reproduce your error right now, but I think the forecasts should still be parsed, yet it wouldn't be too valuable for you even if it finished.

**Comment by amarvin** [comment]
Sorry that it took so long to find time to work on this. I see the same issue with the weekly forecast scraping hanging.

**Comment by amarvin** [comment]
I just released v1.0.9 with a fix for you. Let me know if it works.
