### ISSUE TITLE
Cannot input current week

### ISSUE THREAD

**Issue by briankwada** [amarvin/fantasy-football-bot#42]
Hi,

Really interested in using your team optimizer for the upcoming fantasy season. 

When I try to assign the week variable it gives me the error:
 156     soup = bs(r.text, 'lxml')
    157     span = soup.select_one('li.Navitem.current a.Navtarget')
--> 158     week = span.text.split()[1]
    159     week = int(week)
    160 

AttributeError: 'NoneType' object has no attribute 'text'

Thank you

**Comment by amarvin** [comment]
Thanks for your interest and for reporting the issue. It's been tough to find time during Covid to work on this, but I'll take a look.

Seems like the public league ID that I was using for querying the current week is no longer active.

**Comment by briankwada** [comment]
Completely understandable Alex.
Thanks for replying.
I hope you are doing well despite covid.

Thank you
On Sep 5, 2020, at 5:19 PM, Alex Marvin <notifications@github.com> wrote:

﻿

Thanks for your interest and for reporting the issue. It's been tough to find time during Covid to work on this, but I'll take a look.

Seems like the public league ID that I was using for querying the current week is no longer active.

**Comment by amarvin** [comment]
Thanks, I hope you're doing well too. I just released `v1.0.9` with a fix for you. Let me know if it works.

**Comment by briankwada** [comment]
Will do. Thanks.
Thought this would be an interesting way to play the season.

On Sep 5, 2020, at 6:47 PM, Alex Marvin <notifications@github.com> wrote:

﻿

Thanks, I hope you're doing well too. I just released v1.0.9 with a fix for you. Let me know if it works.

**Comment by briankwada** [comment]
Works great Alex.
Thank you

On Sep 5, 2020, at 7:13 PM, Brian Wada <briankwada@hotmail.com> wrote:

﻿
Will do. Thanks.
Thought this would be an interesting way to play the season.

On Sep 5, 2020, at 6:47 PM, Alex Marvin <notifications@github.com> wrote:

﻿

Thanks, I hope you're doing well too. I just released v1.0.9 with a fix for you. Let me know if it works.
