### ISSUE TITLE
Update PUBLIC_LEAGUE

### ISSUE THREAD

**Issue by ghost** [amarvin/fantasy-football-bot#56]
Reported via email by keithaaronsouth@gmail.com:

> Hi Alex,
> 
>I'm sorry to bother you but I was wondering if you had a quick answer to the trouble I'm having using your github project ffbot?
> 
> When I enter "week = ffbot.current_week()" I get an unexpected result. Also, after "df = ffbot.scrape(LEAGUE)" I do get "Scraping all QB..." but that's it.
> 
> ```py
> >> week = ffbot.current_week()
> Traceback (most recent call last):
>   File "C:\Users\keith\AppData\Local\Programs\Python\Python310\lib\code.py", line 90, in runcode
>     exec(code, self.locals)
>   File "<input>", line 1, in <module>
>   File "C:\Users\keith\PycharmProjects\fantasy-football-bot\ffbot\scraper.py", line 175, in current_week
>     week = span.text.split()[1]
> AttributeError: 'NoneType' object has no attribute 'text'
> >> df = ffbot.scrape(LEAGUE)
> 2022-08-24 10:21:56.774 | INFO     | ffbot.scraper:scrape:47 - Scraping all QB...
> Traceback (most recent call last):
>  File "C:\Users\keith\AppData\Local\Programs\Python\Python310\lib\code.py", line 90, in runcode
>     exec(code, self.locals)
>  File "<input>", line 1, in <module>
> ```
> 
>I'm using [someone's public league/team](https://football.fantasysports.yahoo.com/f1/76554/9) to test, since I haven't set up my league/team yet.
> 
>Thanks, if you have the time for this noob,
>Keith

Thanks, Keith for reporting this! It seems like a repeat of #42 and #47, whereby the public league ID used in `ffbot.current_week()` is no longer an active public league in this year's fantasy football season.

**Comment by amarvin** [comment]
A new release v1.1.1 that includes this fix has now been published to PyPI.
