### ISSUE TITLE
load not saving static variables

### ISSUE THREAD

**Issue by JAWEEWAJ** [amarvin/fantasy-football-bot#66]
looks like load doesn't load in the data from last entry

```py
>>> df, week = ffbot.load() 
>>> df = ffbot.scrape(LEAGUE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'LEAGUE' is not defined
```

**Comment by amarvin** [comment]
That error traceback shows that load worked, as the error is on the next line. To get that next line to work, it says you need to define the variable LEAGUE, which is your league ID.

**Comment by JAWEEWAJ** [comment]
Correct. But then I need to define it every week (or day depending on how
often) when I run the script. It would be good to load it in to avoid
having to reenter all the data every time.

**Comment by amarvin** [comment]
Hmm, aren't you saving this Python script anyway and just rerunning it every week/day? Just add an extra line.
