### ISSUE TITLE
Fix bug with scraper for player ID, given new HTML element

### ISSUE THREAD

**Issue by amarvin** [amarvin/fantasy-football-bot#77]
Seems like Yahoo did a minor change to the player details view replacing a `<span>` with a `<div>`, and that breaks the `ffbot.scape`'s CSS selector for player ID.

**Comment by Incogneat01234** [comment]
I saw this pop up, any thoughts on a quick fix? I am using your scraper to pull data for a trade-finding tool and noticed yahoo broke this a few days ago.

**Comment by amarvin** [comment]
I'm building the fix now and will push a new version v1.2.4 with it to PyPI. You should then be able to just run `pip install -U ffbot` to get the fix.

**Comment by amarvin** [comment]
v1.2.4 is published and ready for you.
