### ISSUE TITLE
Discounted points?

### ISSUE THREAD

**Issue by vsg-sandi** [amarvin/fantasy-football-bot#94]
Hi!
Thanks for the work you put into this. I may have a silly question for you. I’m new to Fantasy Football but did google and search yahoo’s docs but didn’t find the answer. 

What exactly is “Discounted Points” as used in the optimization results?

Just trying to fully understand the output so I know I’m making logical choices based on the data. 

Thanks for the help!

**Comment by amarvin** [comment]
Thanks @vsg-sandi for your interest in `ffbot`! Good question about "Discounted Points". It's a term I invented for `ffbot` and isn't found in Yahoo Fantasy Football documentation. Someone else asked the same question, so I'll link my answer: https://github.com/amarvin/fantasy-football-bot/issues/75#issuecomment-1712168117. I hope that helps!
